- name: Grant root permissions
  hosts: all
  become: true
  become_user: root
  tasks:
    -name: Add user to sidoers group
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: "{{ user }}ALL=(ALL)NOPASWD:ALL"
     vars:
       user: ansible
- hosts: workers 
  #connection: local
  become: true
  #become_user: root
  roles:
  - base

- hosts: masters
  #connection: local
  become: true
  #become_user: root
  roles:
  - base

- hosts: workers
  #connection: local
  become: true
  # become_user: aca
  roles:
  - ubuntu #rocky

- hosts: masters
  #connection: local
  become: true
  # become_user: root
  roles:
  - ubuntu

- hosts: masters
  #connection: local
  become: true
  #become_user: root
  roles:
  - initkubernetes
#
- hosts: workers
  become: true
  #become_user: aca
  roles:
  - worker-join
