- hosts: all
  become: true
  roles:
  - base


- hosts: all
  become: true
  tasks:
    - name: Choose Linux distro and run it's roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
      - "{{ ansible_distribution }}"

- hosts: masters
  become: true
  roles:
  - initkubernetes

- hosts: workers
  become: true
  roles:
  - worker-join
